version: "3.7"

services:

##### user
  user:
    image: node:dubnium
    container_name: user
    working_dir: /opt/api/user
    command: npm run docker:debug
    depends_on:
      - user-postgres
    ports:
      - 8001:9901 # node inspect user
    env_file:
      - ./docker/env/common.env
      - ./docker/env/user.env
    volumes:
      - ./src/services/user:/opt/api/user

  user-postgres:
    image: postgres:latest
    container_name: user-postgres
    restart: always
    ports: # for debug puproses, remove in the production
      - 5533:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGPORT=5432
    volumes:
      - ./src/services/user/db:/opt/api/user/db

##### book
  book:
    image: node:dubnium
    container_name: book
    working_dir: /opt/api/book
    command: npm run docker:debug
    depends_on:
      - book-postgres
    ports:
      - 8002:9901 # node inspect book
    env_file:
      - ./docker/env/common.env
      - ./docker/env/book.env
    volumes:
      - ./src/services/book:/opt/api/book

  book-postgres:
    image: postgres:latest
    container_name: book-postgres
    restart: always
    ports: # for debug puproses, remove in the production
      - 5534:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGPORT=5432
    volumes:
      - ./src/services/book/db:/opt/api/book/db
