version: "3.7"

services:

##### user

  user-postgres:
    image: postgres:latest
    container_name: user-postgres
    restart: always
    ports: # for debug, remove in the production
      - 5532:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGPORT=5432
    volumes:
      - ./src/packages/user/db:/opt/api/user/db

##### todo

  todo-postgres:
    image: postgres:latest
    container_name: todo-postgres
    restart: always
    ports: # for debug, remove in the production
      - 5533:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGPORT=5432
    volumes:
      - ./src/packages/todo/db:/opt/api/todo/db

#### envoy-api

  envoy-api:
    image: envoy:latest
    container_name: envoy-api
    build:
      context: ./docker/envoy
      dockerfile: Dockerfile
    ports:
      - 8080:8080
