version: "3.7"

services:

##### user
  user:
    image: node:dubnium
    container_name: user
    working_dir: /home/api/user
    command: npm run docker:debug
    depends_on:
      - user-postgres
    ports:
      - 8001:9229 # node inspect user
    env_file:
      - ./environments/common.env
      - ./environments/user.env
    environment:
      - GRPC_VERBOSITY=DEBUG
    volumes:
      - ./src/packages/user:/home/api/user

  user-postgres:
    image: postgres:latest
    container_name: user-postgres
    restart: always
    ports: # for debug puproses, remove in the production
      - 5532:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGPORT=5432
    volumes:
      - ./src/packages/user/db:/home/api/user/db

##### todo
  todo:
    image: node:dubnium
    container_name: todo
    working_dir: /home/api/todo
    command: npm run docker:debug
    depends_on:
      - todo-postgres
    ports:
      - 8002:9229 # for debug puproses, remove in the production
    env_file:
      - ./environments/common.env
      - ./environments/todo.env
    volumes:
      - ./src/packages/todo:/home/api/todo

  todo-postgres:
    image: postgres:latest
    container_name: todo-postgres
    restart: always
    ports: # for debug puproses, remove in the production
      - 5533:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - PGPORT=5432
    volumes:
      - ./src/packages/todo/db:/home/api/todo/db

#### envoy-api
  envoy-api-dev:
    image: envoyproxy/envoy:latest
    container_name: envoy-api-dev
    working_dir: /home/envoy
    command: /usr/local/bin/envoy -c /home/envoy/envoy.json
    ports:
      - 443:443
    volumes:
      - ./envoy:/home/envoy
