version: "3.7"

services:

  ##### user
  user:
    image: node:erbium
    container_name: user
    working_dir: /home/api/
    command: node_modules/.bin/nest start user --debug --watch
    depends_on:
      - api-postgres
    ports:
      - 8001:9229 # node inspect
    env_file:
      - environments/common.env
      - environments/user.env
    volumes:
      - ..:/home/api

  ##### auth
  auth:
    image: node:erbium
    container_name: auth
    working_dir: /home/api/
    command: node_modules/.bin/nest start auth --debug --watch
    depends_on:
      - user
    ports:
      - 8002:9229 # node inspect
    env_file:
      - environments/common.env
      - environments/auth.env
    volumes:
      - ..:/home/api

  ##### chat
  chat:
    image: node:erbium
    container_name: chat
    working_dir: /home/api/
    command: node_modules/.bin/nest start chat --debug --watch
    depends_on:
      - user
    ports:
      - 8003:9229 # node inspect
    env_file:
      - environments/common.env
      - environments/chat.env
    volumes:
      - ..:/home/api

  #### api postgres
  api-postgres:
    container_name: api-postgres
    image: postgres:11
    restart: always
    ports: # for debug puproses, remove in the production
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=user,chat
      - PGPORT=5432
    volumes:
      - ./postgres/scripts:/docker-entrypoint-initdb.d
      # - ./postgres/data:/var/lib/postgresql/data

  #### envoy-api
  envoy-api-dev:
    image: envoyproxy/envoy-alpine:v1.12.3
    container_name: envoy-api-dev
    working_dir: /home/envoy
    command: /usr/local/bin/envoy -c /home/envoy/envoy.json
    ports:
      - 443:443
    volumes:
      - ./envoy:/home/envoy
